# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwallet',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_wallet', serialize=False, to='wallet.Wallet'),
        ),
    ]
