# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
