# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct'), ('ico', 'ICO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
