# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20170822_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='success',
            new_name='transferred',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sys_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
